# Generated by Django 3.2.5 on 2021-07-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Maths', 'Mathematics'), ('Eng', 'English'), ('LO', 'Life Orientation'), ('LS', 'Life Sciences'), ('Physics', 'Physical Sciences')], default='English', max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.learner')),
            ],
        ),
    ]
