# Generated by Django 3.2.5 on 2021-07-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210723_1919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
