# Generated by Django 3.2.5 on 2021-07-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(choices=[('Eng', 'English'), ('Physics', 'Physical Sciences'), ('Maths', 'Mathematics'), ('LO', 'Life Orientation'), ('LS', 'Life Sciences')], default='English', max_length=200),
        ),
    ]
