# Generated by Django 3.2.5 on 2021-07-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
